# -*- coding: utf-8 -*-
"""Calculate Accuracy Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def accuracy_score(y_true, y_pred):
	# Your code here
	acc = 0
	for i in range(len(y_true)):
		if y_true[i]==y_pred[i]:
			acc += 1
		else:
			pass
	acc = acc/len(y_true)

	return acc