# -*- coding: utf-8 -*-
"""Feature Scaling Implementation Easy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def feature_scaling(data: np.ndarray) -> (np.ndarray, np.ndarray):
    # Your code here
    mean = np.mean(data, axis=0)
    std_dev = np.std(data, axis=0)
    standardized_data = (data - mean) / std_dev

    mini = np.min(data, axis=0)
    maxi = np.max(data, axis=0)
    normalized_data = (data - mini) / (maxi - mini)

    return standardized_data, normalized_data