# -*- coding: utf-8 -*-
"""Implement Ridge Regression Loss Function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def ridge_loss(X: np.ndarray, w: np.ndarray, y_true: np.ndarray, alpha: float) -> float:
	# Your code here
    z = np.dot(X, w)
    error = 0
    for i in range(len(y)):
        error += (y[i]-z[i])**2
    error = error/len(y)
    reg = 0
    for j in range(len(w)):
        reg += w[j]**2
    loss = error + alpha*reg

	return loss