# -*- coding: utf-8 -*-
"""Implement Precision Metric

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np
def precision(y_true, y_pred):
	# Your code here
    tp = 0
    fp =0
	for i in range(len(y_true)):
        if (y_true[i]==1) & (y_pred[i]==1):
            tp += 1
        elif (y_true[i]==0) & (y_pred[i]==1):
            fp+=1
        else:
            pass
    return tp/(tp+fp)