# -*- coding: utf-8 -*-
"""Implement K-Nearest Neighbors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ddSTk9mzwXrGGcc23dWtWNcJd2Z_g0b
"""

import numpy as np
def k_nearest_neighbors(points, query_point, k):
    """
    Find k nearest neighbors to a query point

    Args:
        points: List of tuples representing points [(x1, y1), (x2, y2), ...]
        query_point: Tuple representing query point (x, y)
        k: Number of nearest neighbors to return

    Returns:
        List of k nearest neighbor points as tuples
    """
    if k <= 0:
        return []
    k = min(k, len(points))

    P = np.array(points, dtype=float)
    q = np.array(query_point, dtype=float)

    d = np.linalg.norm(P - q, axis=1)
    idx = np.argsort(d)[:k]
    return [tuple(points[i]) for i in idx]