# -*- coding: utf-8 -*-
"""Implement K-Fold Cross-Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True):
    """
    Implement k-fold cross-validation by returning train-test indices.
    """
    index = np.arange(len(X))
    if shuffle:
        np.random.shuffle(index)

    sizes = np.full(k, len(X) // k, dtype=int)
    sizes[:len(X) % k] += 1

    start = 0
    folds = []
    for size in sizes:
        stop = start + size
        testfold = index[start:stop]
        trainfold = np.concatenate([index[:start], index[stop:]])
        folds.append((trainfold, testfold))
        start = stop

    return folds