# -*- coding: utf-8 -*-
"""Linear Kernel Function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def kernel_function(x1, x2):
	# Your code here
	return np.sum(np.dot(x1, x2))