# -*- coding: utf-8 -*-
"""One-Hot Encoding of Nominal Values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def to_categorical(x, n_col=None):
	# Your code here
    n = len(x)
    maxvalue = np.max(x)
    if n_col is not None:
        output = np.zeros((n,n_col))
    else:
        output = np.zeros((n,maxvalue+1))
    for i in range(len(x)):
        hotcode = x[i]
        output[i][hotcode] = 1
    return output