# -*- coding: utf-8 -*-
"""Calculate Correlation Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def calculate_correlation_matrix(X, Y=None):
	# Your code here
    stdx = np.sqrt(np.mean((X - X.mean(axis=0))**2, axis=0))
    stdx = np.expand_dims(stdx, 1)
    n_samples = X.shape[0]
    if Y is not None:
        stdy = np.sqrt(np.mean((Y - Y.mean(axis=0))**2, axis=0))
        stdy = np.expand_dims(stdy, 1)
        cov = (1 / n_samples) * (X - X.mean(axis=0)).T.dot(Y - Y.mean(axis=0))
        corr = cov/(stdx.dot(stdy.T))
    else:
        cov = (1 /n_samples) * (X - X.mean(axis=0)).T.dot(X - X.mean(axis=0))
        corr = cov/(np.dot(stdx, stdx.T))

	return corr