# -*- coding: utf-8 -*-
"""Calculate Mean by Row or Column.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
    if mode == "column":
        means = np.mean(matrix, axis=0)
    else:
        means = np.mean(matrix, axis=1)

    return means.tolist()