# -*- coding: utf-8 -*-
"""Calculate Covariance Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
    vectors = np.array(vectors)
    return np.cov(vectors).tolist()