# -*- coding: utf-8 -*-
"""Convert Vector to Diagonal Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def make_diagonal(x):
    identity_matrix = np.identity(np.size(x))
    return (identity_matrix*x)