# -*- coding: utf-8 -*-
"""Determinant of a 4x4 Matrix using Laplace's Expansion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

def determinant_4x4(matrix: list[list[int | float]]) -> float:

    if len(matrix) == 1:
        return matrix[0][0]


    det = 0
    for c in range(len(matrix)):

        minor = [row[:c] + row[c+1:] for row in matrix[1:]]

        cofactor = ((-1) ** c) * determinant_4x4(minor)

        det += matrix[0][c] * cofactor

    return det