# -*- coding: utf-8 -*-
"""Eigenvalues of a Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np
def calculate_eigenvalues(matrix: list[list[float|int]]) -> list[float]:
    matrix = np.array(matrix)
    eigenvalues = np.linalg.eigvals(matrix)
    return eigenvalues.tolist()