# -*- coding: utf-8 -*-
"""Matrix Transformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def transform_matrix(A: list[list[int | float]], T: list[list[int | float]], S: list[list[int | float]]) -> list[list[int | float]] | int:
    T1 = np.linalg.inv(T)
    transformed_matrix = np.matmul(np.matmul(T1, A), S)

    for i in range(1, len(transformed_matrix)):
        if np.array_equal(transformed_matrix[i], transformed_matrix[i - 1]):
            return -1

    return transformed_matrix.tolist()