# -*- coding: utf-8 -*-
"""Matrix times Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def matrixmul(a: list[list[int | float]], b: list[list[int | float]]) -> list[list[int | float]] | int:
    a = np.array(a)
    b = np.array(b)

    if a.shape[1] != b.shape[0]:  # check dimensions for matrix multiplication
        return -1

    c = np.matmul(a, b)
    return c.tolist()