# -*- coding: utf-8 -*-
"""Reshape Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
    a = np.array(a)
	if (new_shape[0]*new_shape[1]) != (a.size):
        return []
    reshaped_matrix = np.reshape(a, new_shape).tolist()
	return reshaped_matrix