# -*- coding: utf-8 -*-
"""Scalar Multiplication of a Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def scalar_multiply(matrix: list[list[int | float]], scalar: int | float) -> list[list[int | float]]:
    matrix = np.array(matrix)
    return (matrix * scalar).tolist()