# -*- coding: utf-8 -*-
"""Transpose.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Wxa7UNr4uh0oeOQLMLvElQSg5JlIEai
"""

import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    a = np.array(a)
	return a.T