# -*- coding: utf-8 -*-
"""Transformation Matrix from Basis B to C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np

def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:
    Cinv = np.linalg.inv(C)
    P = np.dot(Cinv, B)
    return P.tolist()