# -*- coding: utf-8 -*-
"""Implementation of Log Softmax Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import numpy as np
import math
def log_softmax(scores: list) -> np.ndarray:
	# Your code here
	maxa = max(scores)
	logsoft = np.zeros((len(scores)))
	s = 0
	for i in range(len(scores)):
		s += math.exp(scores[i]-maxa)
	for i in range(len(scores)):
		logsoft[i] = scores[i]-maxa -math.log(s)
	return logsoft