# -*- coding: utf-8 -*-
"""Implement ReLU Activation Function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

def relu(z: float) -> float:

	return max(z, 0)