# -*- coding: utf-8 -*-
"""Muon Optimizer Update with Newton-Schulz Iteration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ddSTk9mzwXrGGcc23dWtWNcJd2Z_g0b
"""

import numpy as np

def newtonschulz5(G: np.ndarray, steps=5, eps=1e-7) -> np.ndarray:
    """
    Apply the Newton-Schulz (quintic) iteration for 5 steps to matrix G.
    Args:
        G: 2D NumPy array
        steps: Number of iteration steps (default 5)
        eps: Small constant for stability
    Returns:
        Matrix after Newton-Schulz iteration
    """
    # Your code here
    X = G.astype(np.float64, copy=True)
    transposed = False
    if X.shape[0] > X.shape[1]:
        X = X.T
        transposed = True
    frob = np.linalg.norm(X, ord='fro')
    if frob < eps:
        # If G is (near) zero, orthogonalization is ill-defined; return zeros
        X = np.zeros_like(X)
    else:
        X = X / (frob + eps)


    a = 3.4445
    b = -4.7750
    c = 2.0315

    # Iteration: X <- (aI + bA + cA^2) X, where A = XX^T
    for _ in range(steps):
        A = X @ X.T                  # square
        A2 = A @ A
        B = b * A + c * A2
        X = a * X + B @ X

    # Transpose back if needed
    if transposed:
        X = X.T
    return X


def muon_update(theta: np.ndarray, grad: np.ndarray, B_prev: np.ndarray, mu: float, lr: float) -> tuple:
    """
    Performs one Muon optimizer update (Algorithm 2). Returns the updated parameter, new B, and the preconditioned update.
    Args:
        theta: Parameter matrix (2D NumPy array)
        grad: Gradient matrix (same shape)
        B_prev: Previous B matrix (momentum)
        mu: Momentum factor (0 <= mu < 1)
        lr: Learning rate (step size)
    Returns:
        theta_new: Updated parameter matrix
        B_new: Updated B matrix
        O: Preconditioned update
    """
    # Step 1: Compute B_t
    # Step 2: Precondition with Newton-Schulz5
    # Step 3: Update theta
    # Your code here
    Bt = mu*B_prev+grad
    Ot = newtonschulz5(Bt, steps=5, eps=1e-7)
    theta -= lr*Ot
    return theta, Bt, Ot