# -*- coding: utf-8 -*-
"""Sigmoid Activation Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import math
def sigmoid(z: float) -> float:
  result = 1 / (1 + math.exp(-z))
  return round(result, 4)