# -*- coding: utf-8 -*-
"""Softmax Activation Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Cu3AiEXBXwwC2Yi_1G8lUqeCWUl3AO
"""

import math

def softmax(scores: list[float]) -> list[float]:
    # Exponentiate scores
    for i in range(len(scores)):
        scores[i] = math.exp(scores[i])

    total = sum(scores)
    probabilities = []
    for i in range(len(scores)):
        probabilities.append(scores[i] / total)

    return probabilities